#!/usr/bin/env node
'use strict';

/**
 * scripts/generate-app-env.js
 *
 * Reads .env + .env.<ENVIRONMENT> (or process.env in env-var mode) and
 * generates a separate .env.<environment>.<app-name> file for each app —
 * containing the variables that load-env.js would inject at runtime.
 *
 * PORT is only included when explicitly configured (PREFIX__PORT in config
 * files or process.env.PORT from the platform). No PORT is auto-derived.
 *
 * Usage:
 *   node scripts/generate-app-env.js                      # all apps, auto-detect env
 *   node scripts/generate-app-env.js production            # all apps, explicit env
 *   node scripts/generate-app-env.js production pos-auth   # single app, explicit env
 *   node scripts/generate-app-env.js -- pos-auth           # single app, auto-detect env
 *
 * Output:
 *   .env.<environment>.pos-auth
 *   .env.<environment>.pos-stock
 *   .env.<environment>.pos-strapi
 *   .env.<environment>.rutba-web
 *   … (one file per app)
 */

const fs = require('fs');
const path = require('path');

const {
  ROOT,
  getAppDirs,
  getAppPrefixes,
  resolveAllVariables,
  splitVariables,
  validateVariables,
  buildEnvForApp,
} = require('./env-utils');

// ── CLI parsing ────────────────────────────────────────────

const cliArgs = process.argv.slice(2);
let environmentOverride;
let filterApp;

for (const arg of cliArgs) {
  if (arg === '--') continue;
  // If it looks like an app name (contains a hyphen), treat it as a filter
  if (arg.includes('-')) {
    filterApp = arg;
  } else {
    environmentOverride = arg;
  }
}

// ── 1. Resolve variables ──────────────────────────────────

const { mode, environment, vars } = resolveAllVariables({
  environmentOverride,
});

const allApps = getAppDirs();
const allPrefixes = getAppPrefixes();
const { globals, appVars, allOrigins } = splitVariables(vars, allPrefixes);

console.log(`[generate-app-env] Mode: ${mode} | Environment: ${environment}`);

// ── 2. Validate ───────────────────────────────────────────

const { errors, warnings } = validateVariables(
  globals, appVars, allPrefixes,
);

for (const w of warnings) console.warn(`[generate-app-env] WARN: ${w}`);
if (errors.length) {
  for (const e of errors) console.error(`[generate-app-env] ERROR: ${e}`);
  console.error(
    `[generate-app-env] ${errors.length} required variable(s) missing — aborting.`
  );
  process.exit(1);
}

// ── 3. Determine which apps to generate ───────────────────

let appsToGenerate = allApps;

if (filterApp) {
  const match = allApps.find((a) => a.dir === filterApp);
  if (!match) {
    console.error(
      `[generate-app-env] Unknown app: ${filterApp}\n` +
      `  Available: ${allApps.map((a) => a.dir).join(', ')}`
    );
    process.exit(1);
  }
  appsToGenerate = [match];
}

// ── 4. Generate per-app env files ─────────────────────────

const generated = [];

for (const { dir, prefix } of appsToGenerate) {
  const envForApp = buildEnvForApp({
    targetDir: dir,
    targetPrefix: prefix,
    globals,
    appVars,
    allOrigins,
    // No platformPort — file generation shows config-derived values only
  });

  // Build file content
  const lines = [
    '# ============================================================',
    `# .env.${environment}.${dir}`,
    `# Auto-generated by scripts/generate-app-env.js`,
    `# Mode: ${mode} | Environment: ${environment} | App: ${dir} (${prefix})`,
    '#',
    '# This file shows exactly what load-env.js would inject at runtime.',
    '# Do NOT edit — re-generate with:',
    `#   node scripts/generate-app-env.js ${environment} ${dir}`,
    '# ============================================================',
    '',
  ];

  // Sort keys into sections for readability
  const appSpecificKeys = new Set(Object.keys(appVars[prefix] || {}));
  const derivedKeys = new Set(['CORS_ORIGINS']);
  const globalEntries = [];
  const appEntries = [];
  const derivedEntries = [];

  for (const [key, value] of Object.entries(envForApp)) {
    if (derivedKeys.has(key) && !appSpecificKeys.has(key)) {
      derivedEntries.push([key, value]);
    } else if (appSpecificKeys.has(key)) {
      appEntries.push([key, value]);
    } else {
      globalEntries.push([key, value]);
    }
  }

  if (globalEntries.length) {
    lines.push(`# --- Global variables ---`);
    for (const [k, v] of globalEntries) {
      lines.push(`${k}=${v}`);
    }
    lines.push('');
  }

  if (appEntries.length) {
    lines.push(`# --- ${prefix} app-specific (prefix stripped) ---`);
    for (const [k, v] of appEntries) {
      lines.push(`${k}=${v}`);
    }
    lines.push('');
  }

  if (derivedEntries.length) {
    lines.push(`# --- Derived / auto-computed ---`);
    for (const [k, v] of derivedEntries) {
      lines.push(`${k}=${v}`);
    }
    lines.push('');
  }

  const outFileName = `.env.${environment}.${dir}`;
  const outPath = path.join(ROOT, outFileName);
  fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
  generated.push(outFileName);
}

// ── 5. Summary ────────────────────────────────────────────

console.log(
  `[generate-app-env] Generated ${generated.length} file(s):`
);
for (const f of generated) {
  console.log(`  ${f}`);
}
