'use strict';

// TypeScript client generator. Reads an api-interface (from .api-pro/ or DB)
// and emits a TS module string that wraps each method as a typed function on
// a StrapiClient.
//
// Existing scaffold-runner.js is a linter (route-token vs signature alignment);
// this file is the actual code generator the Admin UI's "Scaffold" button
// downloads / displays.

const fileStore = require('./file-store');

const INTERFACE_UID = 'plugin::api-pro.api-interface';
const METHOD_UID = 'plugin::api-pro.api-interface-method';

const CRUD_OPTIONS = {
  find:    ['filters', 'populate', 'fields', 'pagination', 'sort', 'publicationState', 'locale'],
  findOne: ['populate', 'fields', 'publicationState', 'locale'],
  create:  ['populate', 'fields'],
  update:  ['populate', 'fields'],
  delete:  [],
};

function camelCase(input) {
  return String(input || '')
    .replace(/[-_\s]+([a-z0-9])/gi, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (c) => c.toLowerCase());
}

// Replace :tokenName with ${tokenName} in a route path so it becomes a TS
// template literal interpolation.
function templatizePath(path) {
  return String(path || '').replace(/:([a-zA-Z_][\w]*)/g, (_, name) => `\${${name}}`);
}

// Sniff which query-option keys this method accepts. Falls back to the union
// of all CRUD options when the action isn't a recognized verb.
function queryOptionsForMethod(method) {
  const action = String(method.action || method.name || '').toLowerCase();
  if (CRUD_OPTIONS[action]) return CRUD_OPTIONS[action];
  const allKeys = new Set();
  Object.values(CRUD_OPTIONS).forEach((arr) => arr.forEach((k) => allKeys.add(k)));
  return Array.from(allKeys);
}

// Resolves which Strapi client verb to call.
function clientVerbForMethod(method) {
  const httpMethod = String(method.method || 'GET').toLowerCase();
  if (httpMethod === 'patch') return 'put'; // collapse PATCHâ†’put for StrapiClient
  return ['get', 'post', 'put', 'delete'].includes(httpMethod) ? httpMethod : 'get';
}

function emitMethod(method) {
  const name = method.name || method.action || method.key;
  const path = templatizePath(method.path);
  const verb = clientVerbForMethod(method);
  const tokens = Array.isArray(method.routeTokens) ? method.routeTokens : [];
  const optionKeys = queryOptionsForMethod(method);

  const positionalArgs = tokens.map((t) => `${t}: string`);
  const bodyArg = ['post', 'put'].includes(verb) ? 'body?: Record<string, unknown>' : null;
  const optionsArg = optionKeys.length > 0
    ? `{ ${optionKeys.join(', ')} }: { ${optionKeys.map((k) => `${k}?: unknown`).join('; ')} } = {}`
    : null;

  const args = [...positionalArgs, ...(bodyArg ? [bodyArg] : []), ...(optionsArg ? [optionsArg] : [])].join(', ');
  const paramsObject = optionKeys.length > 0
    ? `{ params: { ${optionKeys.join(', ')} } }`
    : null;

  let callArgs;
  if (verb === 'get' || verb === 'delete') {
    callArgs = paramsObject ? `\`${path}\`, ${paramsObject}` : `\`${path}\``;
  } else {
    // post / put â€” first body, then options
    const body = bodyArg ? 'body' : '{}';
    callArgs = paramsObject ? `\`${path}\`, ${body}, ${paramsObject}` : `\`${path}\`, ${body}`;
  }

  return `    ${name}: (${args}) =>\n      client.${verb}(${callArgs}),`;
}

function emitInterface({ key, name, methods }) {
  const fnName = `${camelCase(key)}Api`;
  const methodsCode = methods.map(emitMethod).join('\n\n');
  return [
    `// Auto-generated by api-pro â€” do not edit manually.`,
    `// Interface: ${name || key}`,
    `import type { StrapiClient } from '../client';`,
    ``,
    `export function ${fnName}(client: StrapiClient) {`,
    `  return {`,
    methodsCode,
    `  };`,
    `}`,
    ``,
  ].join('\n');
}

// Build the scaffold from the file-store (authoritative). Falls back to DB
// if the file is missing â€” useful while authoring before the first save.
async function generate(strapi, interfaceKey) {
  const fileData = await fileStore.readInterface(strapi, interfaceKey);
  if (fileData) {
    return {
      code: emitInterface({
        key: fileData.key || interfaceKey,
        name: fileData.name || fileData.label || interfaceKey,
        methods: Array.isArray(fileData.methods) ? fileData.methods : [],
      }),
      source: 'file',
    };
  }

  const row = await strapi.db.query(INTERFACE_UID).findOne({
    where: { key: interfaceKey },
    populate: { methods: true },
  });
  if (!row) {
    const err = new Error(`Interface '${interfaceKey}' not found`);
    err.status = 404;
    throw err;
  }

  return {
    code: emitInterface({
      key: row.key,
      name: row.name,
      methods: Array.isArray(row.methods) ? row.methods : [],
    }),
    source: 'db',
  };
}

module.exports = {
  generate,
  emitInterface,
  emitMethod,
  templatizePath,
  camelCase,
};
