#!/usr/bin/env node
'use strict';

/**
 * Upload tranche smoke. Marker-only and self-cleaning: every file it creates is
 * named with the marker and removed at the end, along with its row, its links
 * and the bytes the provider wrote.
 *
 * Runs against the LOCAL provider regardless of what the environment is
 * configured for — MEDIA_BASE_URL points at the production media host, and a
 * smoke has no business PUTting test images there. Setting neither
 * MEDIA_BASE_URL nor MEDIA_UPLOAD_TOKEN is exactly how the provider is told to
 * store locally (it refuses to guess when only one is present).
 *
 *  A. the plugin surface is reachable and the provider initialises
 *  B. upload() writes a `files` row in the same column shape Strapi writes,
 *     with responsive formats generated by the same sharp code
 *  C. the bytes land where the row's url says they do, and core serves them
 *  D. ref/field/refId links the file to its owner in files_related_mph
 *  E. POST /api/upload over real multipart returns Strapi's bare array
 *  F. DELETE removes the row, the links and the bytes
 *  G. gates: anonymous 401, non-multipart 400, empty 400
 */

const path = require('path');
const fs = require('fs');
const fsp = require('fs/promises');
const os = require('os');
const jwtLib = require('jsonwebtoken');
const { get, loadVars } = require('../src/config/env');
const { getDb, closeDb } = require('../src/db/connection');
const { buildCompatStrapi } = require('../src/compat/strapi');
const { initModules } = require('../src/modules');
const { start } = require('../src/http/server');

// Force the LOCAL backend. Two places hold the value and both have to go:
// config/env's cached map (what the plugins.js factory reads), and process.env
// (what the provider falls back to) — which loadVars() itself populates via
// hydrateProcessEnv, so this must run AFTER that call, not before it.
const vars = loadVars().vars;
for (const k of Object.keys(vars)) {
  if (/MEDIA_BASE_URL|MEDIA_UPLOAD_TOKEN/.test(k)) vars[k] = '';
}
for (const k of Object.keys(process.env)) {
  if (/MEDIA_BASE_URL|MEDIA_UPLOAD_TOKEN/.test(k)) delete process.env[k];
}

const PORT = 4038;
const MARK = '__rutba_core_upload_smoke__';

let failures = 0;
const check = (name, ok, detail) => {
  if (ok) console.log(`  PASS  ${name}`);
  else { failures++; console.log(`  FAIL  ${name}${detail ? ` -- ${detail}` : ''}`); }
};

/** A real PNG, generated with the same sharp Strapi uses. */
async function makePng(dir, name, size = 1200) {
  const sharp = require(path.join(__dirname, '..', '..', 'pos-strapi', 'node_modules', 'sharp'));
  const file = path.join(dir, name);
  await sharp({
    create: { width: size, height: Math.round(size * 0.75), channels: 3, background: { r: 30, g: 90, b: 160 } },
  }).png().toFile(file);
  return file;
}

async function main() {
  buildCompatStrapi();
  initModules();
  const db = getDb();
  const tmp = await fsp.mkdtemp(path.join(os.tmpdir(), 'upload-smoke-'));
  let server = null;
  const createdIds = [];
  let productId = null;
  let smokeSessionId = null;
  let smokeFolderId = null;

  try {
    const { uploadService } = require('../src/platform/upload');

    console.log('A. plugin surface');
    const svc = global.strapi.plugin('upload').service('upload');
    check('strapi.plugin(\'upload\').service(\'upload\') resolves', svc === uploadService);
    let providerOk = true; let providerErr = '';
    try { global.strapi.plugin('upload').provider; } catch (e) { providerOk = false; providerErr = e.message; }
    check('provider initialises (local backend)', providerOk, providerErr);

    const uploadsDir = path.join(
      path.resolve(path.join(__dirname, '..', '..', 'pos-strapi'), get('PUBLIC_DIR', './public')),
      'uploads'
    );

    console.log('\nB. upload() writes a Strapi-shaped row');
    const src = await makePng(tmp, `${MARK}-hero.png`);
    const stat = fs.statSync(src);
    const [created] = await uploadService.upload({
      data: { fileInfo: { name: `${MARK} hero`, alternativeText: `${MARK} alt`, caption: `${MARK} cap` } },
      files: { filepath: src, originalFilename: `${MARK}-hero.png`, mimetype: 'image/png', size: stat.size },
    });
    if (created) createdIds.push(created.id);
    check('returns the created file entity', Boolean(created && created.id), JSON.stringify(created).slice(0, 150));

    const row = created && await db('files').where('id', created.id).first();
    check('row carries name/hash/ext/mime/url', Boolean(row && row.name && row.hash && row.ext
      && row.mime === 'image/png' && row.url), JSON.stringify(row && [row.name, row.hash, row.ext, row.url]));
    check('hash is slug_<10 hex>, exactly as Strapi names files',
      Boolean(row && /_[0-9a-f]{10}$/.test(row.hash)), row && row.hash);
    check('width/height measured', Boolean(row && row.width > 0 && row.height > 0),
      row && `${row.width}x${row.height}`);
    // Compared against the file the provider actually wrote, not the source:
    // optimize() re-encodes images before upload, so the row's size is the
    // post-optimisation one — same as Strapi.
    const storedBytes = row && fs.existsSync(path.join(uploadsDir, `${row.hash}${row.ext}`))
      ? fs.statSync(path.join(uploadsDir, `${row.hash}${row.ext}`)).size : null;
    check('size recorded in kB, matching the bytes actually stored',
      Boolean(row && storedBytes && Math.abs(row.size - storedBytes / 1000) < 0.01),
      row && `${row.size} kB vs ${storedBytes} B`);

    const formats = row && (typeof row.formats === 'string' ? JSON.parse(row.formats) : row.formats);
    check('responsive formats generated (thumbnail at least)',
      Boolean(formats && formats.thumbnail && formats.thumbnail.url && formats.thumbnail.hash),
      JSON.stringify(formats && Object.keys(formats)));
    check('each format carries the fields the storefront reads',
      Boolean(formats && Object.values(formats).every((f) => f.url && f.hash && f.ext && f.mime
        && f.width && f.height && f.size !== undefined)),
      JSON.stringify(formats && Object.values(formats)[0]));

    console.log('\nC. the bytes are where the row says');
    const onDisk = row && fs.existsSync(path.join(uploadsDir, `${row.hash}${row.ext}`));
    check('master written to PUBLIC_DIR/uploads', Boolean(onDisk),
      row && path.join(uploadsDir, `${row.hash}${row.ext}`));

    server = await start(PORT);
    const served = row && await fetch(`http://127.0.0.1:${PORT}${row.url}`);
    check('core serves the new file over /uploads',
      Boolean(served && served.status === 200 && /^image\/png/.test(served.headers.get('content-type') || '')),
      served && `${served.status} ${served.headers.get('content-type')}`);
    const thumb = formats && formats.thumbnail
      && await fetch(`http://127.0.0.1:${PORT}${formats.thumbnail.url}`);
    check('and serves the generated thumbnail', Boolean(thumb && thumb.status === 200),
      thumb && String(thumb.status));

    console.log('\nD. ref/field/refId attaches the file to its owner');
    const product = await db('products').whereNotNull('document_id').first('id', 'document_id');
    productId = product && product.id;
    const src2 = await makePng(tmp, `${MARK}-linked.png`, 400);
    const stat2 = fs.statSync(src2);
    const [linked] = await uploadService.upload({
      data: {
        fileInfo: { name: `${MARK} linked` },
        ref: 'api::product.product', refId: String(productId), field: 'images',
      },
      files: { filepath: src2, originalFilename: `${MARK}-linked.png`, mimetype: 'image/png', size: stat2.size },
    });
    if (linked) createdIds.push(linked.id);
    const link = linked && await db('files_related_mph').where('file_id', linked.id).first();
    check('files_related_mph row written with related_type + field',
      Boolean(link && String(link.related_id) === String(productId)
        && link.related_type === 'api::product.product' && link.field === 'images'),
      JSON.stringify(link));
    check('link order is 1-based within the field', Boolean(link && Number(link.order) >= 1),
      link && String(link.order));

    console.log('\nE. POST /api/upload (real multipart)');
    // Mint a real session rather than borrowing one: an existing row may belong
    // to a blocked or unconfirmed account, and the auth middleware rejects both.
    const user = await db('up_users as u')
      .join('up_users_app_roles_lnk as l', 'l.user_id', 'u.id')
      .where({ 'u.blocked': 0, 'u.confirmed': 1 })
      .first('u.id');
    const { sessionManager } = require('../src/auth/up');
    const refresh = user && await sessionManager.generateRefreshToken(String(user.id), 'upload-smoke', { type: 'refresh' });
    if (refresh) smokeSessionId = refresh.sessionId;
    const access = refresh && await sessionManager.generateAccessToken(refresh.token);
    const token = access && !('error' in access) ? access.token : null;

    const src3 = await makePng(tmp, `${MARK}-http.png`, 300);
    const form = new FormData();
    form.append('files', new Blob([await fsp.readFile(src3)], { type: 'image/png' }), `${MARK}-http.png`);
    form.append('fileInfo', JSON.stringify({ name: `${MARK} http`, alternativeText: `${MARK} http alt` }));

    const anon = await fetch(`http://127.0.0.1:${PORT}/api/upload`, { method: 'POST', body: form });
    check('anonymous upload 401', anon.status === 401, `got ${anon.status}`);

    if (token) {
      const form2 = new FormData();
      form2.append('files', new Blob([await fsp.readFile(src3)], { type: 'image/png' }), `${MARK}-http.png`);
      form2.append('fileInfo', JSON.stringify({ name: `${MARK} http`, alternativeText: `${MARK} http alt` }));
      const res = await fetch(`http://127.0.0.1:${PORT}/api/upload`, {
        method: 'POST', headers: { authorization: `Bearer ${token}` }, body: form2,
      });
      const body = await res.json().catch(() => null);
      check('POST /api/upload 200', res.status === 200, `${res.status} ${JSON.stringify(body).slice(0, 200)}`);
      check('responds with a BARE ARRAY (not the data/meta envelope)',
        Array.isArray(body) && body.length === 1 && body[0].id && body[0].url,
        JSON.stringify(body).slice(0, 200));
      if (Array.isArray(body)) body.forEach((f) => createdIds.push(f.id));
      check('uploaded name/alt came from fileInfo',
        Array.isArray(body) && body[0].name === `${MARK} http`
        && body[0].alternativeText === `${MARK} http alt`,
        JSON.stringify(body && body[0] && [body[0].name, body[0].alternativeText]));

      const notMultipart = await fetch(`http://127.0.0.1:${PORT}/api/upload`, {
        method: 'POST', headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json' },
        body: '{}',
      });
      check('non-multipart body 400', notMultipart.status === 400, `got ${notMultipart.status}`);

      // DELETE answers with the deleted file in API shape, not the raw row.
      const doomed = createdIds[createdIds.length - 1];
      const del = await fetch(`http://127.0.0.1:${PORT}/api/upload/files/${doomed}`, {
        method: 'DELETE', headers: { authorization: `Bearer ${token}` },
      });
      const delBody = await del.json().catch(() => null);
      check('DELETE /api/upload/files/:id returns the file in API shape',
        del.status === 200 && delBody && delBody.id === doomed
        && delBody.documentId && delBody.url && delBody.alternative_text === undefined,
        `${del.status} ${JSON.stringify(delBody).slice(0, 160)}`);
      if (del.status === 200) createdIds.pop();

      const empty = new FormData();
      empty.append('fileInfo', '{}');
      const noFiles = await fetch(`http://127.0.0.1:${PORT}/api/upload`, {
        method: 'POST', headers: { authorization: `Bearer ${token}` }, body: empty,
      });
      check('multipart with no files 400', noFiles.status === 400, `got ${noFiles.status}`);
    } else {
      check('POST /api/upload 200', false, 'no active session to mint a token from');
    }

    console.log('\nG. the repo call sites that needed the plugin');
    // media-library's service and the media controller's folder service are the
    // two places pos-strapi code reaches for strapi.plugin('upload') — they are
    // why uploads blocked the migration, so exercise them directly rather than
    // through their api-pro-gated routes.
    const folder = await global.strapi.plugin('upload').service('folder')
      .create({ name: `${MARK}-folder`, parent: null });
    if (folder) smokeFolderId = folder.id;
    check('folder service creates a folder with a materialised path',
      Boolean(folder && folder.id && /^\/\d+$/.test(folder.path)),
      JSON.stringify(folder && [folder.name, folder.path]));

    const src4 = await makePng(tmp, `${MARK}-folder.png`, 200);
    const mlResult = await global.strapi.service('api::media-library.media-library')
      .uploadToFolder(
        [{ filepath: src4, originalFilename: `${MARK}-folder.png`, mimetype: 'image/png', size: fs.statSync(src4).size }],
        folder && folder.id,
        { name: `${MARK} in folder` }
      );
    const mlFile = Array.isArray(mlResult) ? mlResult[0] : (mlResult && mlResult.files ? mlResult.files[0] : mlResult);
    if (mlFile && mlFile.id) createdIds.push(mlFile.id);
    check('media-library uploadToFolder works through the plugin service',
      Boolean(mlFile && mlFile.id), JSON.stringify(mlResult).slice(0, 200));
    const lnk = mlFile && mlFile.id && await db('files_folder_lnk').where('file_id', mlFile.id).first();
    check('the file is linked to the folder', Boolean(lnk && folder && lnk.folder_id === folder.id),
      JSON.stringify(lnk));

    console.log('\nF. delete removes row, links and bytes');
    const victim = await db('files').where('id', createdIds[createdIds.length - 1]).first();
    if (victim) {
      const victimPath = path.join(uploadsDir, `${victim.hash}${victim.ext}`);
      await uploadService.remove(victim);
      check('row deleted', !(await db('files').where('id', victim.id).first()));
      check('links deleted', !(await db('files_related_mph').where('file_id', victim.id).first()));
      check('bytes deleted', !fs.existsSync(victimPath), victimPath);
      createdIds.pop();
    }
  } finally {
    for (const id of createdIds) {
      const f = await getDb()('files').where('id', id).first();
      if (f) {
        try { await require('../src/platform/upload').uploadService.remove(f); } catch { /* noop */ }
      }
    }
    // Any stray marker rows from a failed run.
    const strays = await getDb()('files').where('name', 'like', `%${MARK}%`);
    for (const f of strays) {
      try { await require('../src/platform/upload').uploadService.remove(f); } catch { /* noop */ }
    }
    if (smokeFolderId) {
      await getDb()('files_folder_lnk').where('folder_id', smokeFolderId).del().catch(() => {});
      await getDb()('upload_folders').where('id', smokeFolderId).del().catch(() => {});
    }
    if (smokeSessionId) {
      await getDb()('strapi_sessions').where('session_id', smokeSessionId).del().catch(() => {});
    }
    await fsp.rm(tmp, { recursive: true, force: true }).catch(() => {});
    if (server) server.close();
    await closeDb();
  }

  console.log(failures === 0 ? '\nALL PASS' : `\n${failures} FAILURE(S)`);
  process.exit(failures === 0 ? 0 : 1);
}

main().catch(async (e) => {
  console.error('SMOKE ERROR:', e.stack);
  try { await closeDb(); } catch { /* noop */ }
  process.exit(1);
});
